print('whats your name: ')
a = input()
print('hello', a)
print('what\'s your name: ')
b = input()
print('hello', b)
print('what\'s your name: ')
c = input()
print('hello', c)
print('what\'s your name: ')
d = input()
